default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_chat_on_gpt
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: ruby_chat_on_gpt_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  host: <%= ENV['DATABASE_URL'] %>
